[2025-02-12T08:28:06.321+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: xcom_dag.branch manual__2025-02-12T08:28:01.967562+00:00 [queued]>
[2025-02-12T08:28:06.344+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: xcom_dag.branch manual__2025-02-12T08:28:01.967562+00:00 [queued]>
[2025-02-12T08:28:06.344+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-02-12T08:28:06.345+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-02-12T08:28:06.345+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-02-12T08:28:06.373+0000] {taskinstance.py:1383} INFO - Executing <Task(BranchPythonOperator): branch> on 2025-02-12 08:28:01.967562+00:00
[2025-02-12T08:28:06.380+0000] {standard_task_runner.py:55} INFO - Started process 124 to run task
[2025-02-12T08:28:06.388+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'xcom_dag', 'branch', 'manual__2025-02-12T08:28:01.967562+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/xcom_dag.py', '--cfg-path', '/tmp/tmpot2p_oro']
[2025-02-12T08:28:06.389+0000] {standard_task_runner.py:83} INFO - Job 107: Subtask branch
[2025-02-12T08:28:06.507+0000] {task_command.py:376} INFO - Running <TaskInstance: xcom_dag.branch manual__2025-02-12T08:28:01.967562+00:00 [running]> on host bb70ba7cbe58
[2025-02-12T08:28:06.637+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=xcom_dag
AIRFLOW_CTX_TASK_ID=branch
AIRFLOW_CTX_EXECUTION_DATE=2025-02-12T08:28:01.967562+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-12T08:28:01.967562+00:00
[2025-02-12T08:28:06.641+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 211, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/xcom_dag.py", line 17, in _branch
    value = ti.xcom_pull(key='my_key', tasks_ids='t1')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got an unexpected keyword argument 'tasks_ids'
[2025-02-12T08:28:06.657+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=xcom_dag, task_id=branch, execution_date=20250212T082801, start_date=20250212T082806, end_date=20250212T082806
[2025-02-12T08:28:06.683+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 107 for task branch (xcom_pull() got an unexpected keyword argument 'tasks_ids'; 124)
[2025-02-12T08:28:06.732+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2025-02-12T08:28:06.810+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
